### ISSUE TITLE
There should be a way to list only posts of a specific user

### ISSUE THREAD

**Issue by diogovk** [marcioj/elixir_blog#13]
Often, the blog reader might me interested in a specific author, but in the way things are currently, the reader can't show all posts of a specific user.

Also users want to list their own posts.

**Comment by marcioj** [comment]
The idea of this blog is to demonstrate how to create a basic CRUD application with authentication, relationships and also some tests. I'd not like to add a lot of pages/functionality without nothing new in the elixir/phoenix perspective.
